### ISSUE TITLE
Allow static configuration in start and build

### ISSUE THREAD

**Issue by larsbs** [tokamakjs/tokamakjs#46]
Allow using static config files like `json` or `yml` to configure start and build.

E.g:

```yml
appName: APP NAME
envVars: 
  - NODE_ENV
  - APP_ENV
indexTemplate: ./src/index.html
publicFolder: ./public
```

or

```json
{
  "appName": "APP NAME",
}
```
